stages:
- stage: org
  displayName: 'env terraform'

  jobs:
  - job: SetupJob
    displayName: 'Setup Job'
    steps:
    - script: |
        ./Impersonate.sh $var1 $var2
      displayName: 'Impersonate SA'

  - job: DeployDev
    displayName: 'Deploy development'
    dependsOn: SetupJob
    steps:
    - script: |
        ./DeployDev $var1 $var2
      displayName: 'Plan Terraform'

  - job: DeploynonProd
    displayName: 'DeploynonProd'
    dependsOn: DeployDev
    steps:
    - script: |
        ./DeploynonProd.sh $var1 $var2
      displayName: 'Deploy Non production'

  - job: DeployProd
    displayName: 'DeployProd'
    dependsOn: DeploynonProd
    steps:
    - script: |
        ./DeployProd.sh $var1 $var2
      displayName: 'Apply Terraform'