# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
publicPerimeterNet:
  userDefinedString: prod # must be globally unique
  additionalUserDefinedString: "perimeter"
  billing_account: #####-#####-#####
  services:
    - logging.googleapis.com
  networks:
    - network_name: <public-perimeter-vpc-name>
      description: The Perimeter VPC
      routing_mode: GLOBAL
      shared_vpc_host: false
      auto_create_subnetworks: false
      delete_default_internet_gateway_routes: true
      peer_project: "" # Production Host Project Name
      peer_network: "" # Production VPC Name
      subnets:
        - subnet_name: public
          subnet_ip: 10.10.0.0/26
          subnet_region: northamerica-northeast1
          subnet_private_access: 'true'
          subnet_flow_logs: 'true'
          description: This subnet is used for the public interface of the fortigate firewall
          log_config:
            aggregation_interval: INTERVAL_1_MIN
            flow_sampling: 0.5
          secondary_ranges: []
      routes: []
      routers: []

privatePerimeterNet:
  userDefinedString: prod # must be globally unique
  additionalUserDefinedString: "perimeter"
  billing_account: #####-#####-#####
  services:
    - logging.googleapis.com
  networks:
    - network_name: <private-perimeter-vpc-name>
      description: The Perimeter VPC
      routing_mode: GLOBAL
      shared_vpc_host: false
      auto_create_subnetworks: false
      delete_default_internet_gateway_routes: true
      peer_project: "" # Production Host Project Name
      peer_network: "" # Production VPC Name
      subnets:
        - subnet_name: private
          subnet_ip: 10.10.0.64/26
          subnet_region: northamerica-northeast1
          subnet_private_access: 'true'
          subnet_flow_logs: 'true'
          description: This subnet is used for the private interface of the fortigate firewall
          log_config:
            aggregation_interval: INTERVAL_1_MIN
            flow_sampling: 0.5
          secondary_ranges: []
      routes: []
      routers: []

haPerimeterNet:
  userDefinedString: prod # must be globally unique
  additionalUserDefinedString: "perimeter"
  billing_account: #####-#####-#####
  services:
    - logging.googleapis.com
  networks:
    - network_name: <ha-perimeter-vpc-name>
      description: The Perimeter VPC
      routing_mode: GLOBAL
      shared_vpc_host: false
      auto_create_subnetworks: false
      delete_default_internet_gateway_routes: true
      peer_project: "" # Production Host Project Name
      peer_network: "" # Production VPC Name
      subnets:
        - subnet_name: hasync
          subnet_ip: 10.10.0.128/26
          subnet_region: northamerica-northeast1
          subnet_private_access: 'true'
          subnet_flow_logs: 'true'
          description: This subnet is used for the HA Sync interface of the fortigate firewall
          log_config:
            aggregation_interval: INTERVAL_1_MIN
            flow_sampling: 0.5
          secondary_ranges: []
      routes: []
      routers: []

managementperimeter:
  userDefinedString: prod # must be globally unique
  additionalUserDefinedString: "perimeter"
  billing_account: #####-#####-#####
  services:
    - logging.googleapis.com
  networks:
    - network_name: <management-perimeter-vpc-name>
      description: The Perimeter VPC
      routing_mode: GLOBAL
      shared_vpc_host: false
      auto_create_subnetworks: false
      delete_default_internet_gateway_routes: true
      peer_project: "" # Production Host Project Name
      peer_network: "" # Production VPC Name
      subnets:
        - subnet_name: management
          subnet_ip: 10.10.0.192/26
          subnet_region: northamerica-northeast1
          subnet_private_access: 'true'
          subnet_flow_logs: 'true'
          description: This subnet is used for the management interface of the fortigate firewall
          log_config:
            aggregation_interval: INTERVAL_1_MIN
            flow_sampling: 0.5
          secondary_ranges: []
      routes: []
      routers: []