stages:
- stage: org_stage
  displayName: 'org terraform'

  jobs:
  - job: setupworkspace
    displayName: 'Setup workspace'
    steps:
    - download: current
      artifact: BootstrapArtifact
      displayName: 'Download Bootstrap Artifact'
    - template: ../templates/securefile-template.yaml
    - script: |
        echo "Cleaning the current environment..."
        rm -rf $(Build.SourcesDirectory)/*

        echo "Moving downloaded artifacts to the source directory..."
        mv $(Pipeline.Workspace)/BootstrapArtifact/* $(Build.SourcesDirectory)/
        mv $(Pipeline.Workspace)/BootstrapArtifact/.* $(Build.SourcesDirectory)/ 2> /dev/null || true

        echo "Current environment contents:"
        ls -l $(Build.SourcesDirectory)/
        echo "Checking if 0-bootstrap exists and listing contents:"
        if [ -d "$(Build.SourcesDirectory)/0-bootstrap" ]; then
          ls -l $(Build.SourcesDirectory)/0-bootstrap/
        else
          echo "0-bootstrap directory not found."
        fi
        echo "Whole env list from sources directory:"
        echo "list 0-bootstrap"
        ls -l 0-bootstrap/

        ls -l $(Build.SourcesDirectory)/
        echo "Terraform version :"
        terraform version
        echo "tf v1.6"
        wget https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_amd64.zip
        unzip terraform_1.6.0_linux_amd64.zip
        sudo mv terraform /usr/local/bin/
        sudo chmod +x /usr/local/bin/terraform
        echo "Terraform version :"
        terraform version
        echo "list bootstrap"
        ls -l 0-bootstrap/
        echo "list hubandspoke"
        ls -l 3-networks-hub-and-spoke/
        echo "set exec permission"
        chmod +x ./automation-scripts/1-org/1-org.sh
        echo "Executing org.sh:"
        echo "which sa is activated"
        gcloud auth list
        python3 ./fix_tfvars_symlinks.py .
        gcloud auth activate-service-account sa-gcp-partners-test@sa-test-gcp.iam.gserviceaccount.com --key-file=$(googleCredentials.secureFilePath)
        gcloud config set project sa-test-gcp
        echo "which sa is activated"
        gcloud auth list
        chmod +x ./scripts/validate-requirements.sh
        export DOMAIN=$DOMAIN
        echo $DOMAIN
        export GOOGLE_APPLICATION_CREDENTIALS=$(googleCredentials.secureFilePath)
        echo $GOOGLE_APPLICATION_CREDENTIALS
        ./automation-scripts/1-org/1-org.sh
      displayName: 'Replace and Confirm Environment'
    - publish: $(System.DefaultWorkingDirectory)
      artifact: OrgArtifact
      displayName: 'Publish Org Environment'

