regions:
  region1:
    name: "northamerica-northeast1"
  region2:
    name: "northamerica-northeast2"
    enabled: false

business_units:
- business_code: "bu1"
  business_unit: "business_unit_1"
  primary_contact: "example_p1@example.com"
  secondary_contact: "example_s1@example.com"
  management:
    env_code: "m"
    billing_code: "m-bu1"
    env_enabled: true
    windows_activation_enabled: true
    firewall_logging_enabled: false
    optional_fw_rules_enabled: false
    vpc_flow_logs_enabled: false
    peering_iap_fw_rules_enabled: false
    base:
      enabled:   true
      projects:
        - id: proj_base_mgt_s1
          type: service
          app:  mgt_base_s1

  identity:
    env_code: "i"
    billing_code: "i-bu1"
    env_enabled: true
    windows_activation_enabled: true
    firewall_logging_enabled: false
    optional_fw_rules_enabled: false
    vpc_flow_logs_enabled: false
    peering_iap_fw_rules_enabled: false
    base:
      enabled:   true
      projects:
        - id: proj_base_idn_s1
          type: service
          app:  idn_base_s1

  development:
    env_code: "d"
    billing_code: "d-bu1"
    env_enabled: true
    windows_activation_enabled: true
    firewall_logging_enabled: false
    optional_fw_rules_enabled: false
    vpc_flow_logs_enabled: false
    peering_iap_fw_rules_enabled: false
    base:
      enabled:   true
      projects:
        - id: proj_base_dev_pub_s1
          type: service
          app:  pub_base_dev_s1
        - id: proj_base_dev_app_s1
          type: service
          app:  app_base_dev_s1
        - id: proj_base_dev_dat_s1
          type: service
          app:  data_base_dev_s1
  nonproduction:
    env_code: "n"
    billing_code: "n-bu1"
    env_enabled: true
    windows_activation_enabled: true
    firewall_logging_enabled: false
    optional_fw_rules_enabled: false
    vpc_flow_logs_enabled: false
    peering_iap_fw_rules_enabled: false
    base:
      enabled:   true
      projects:
        - id: proj_base_np_pub_s1
          type: service
          app:  pub_base_np_s1
        - id: proj_base_np_app_s1
          type: service
          app:  app_base_np_s1
        - id: proj_base_np_dat_s1
          type: service
          app:  data_base_np_s1
  production:
    env_code: "p"
    billing_code: "p-bu1"
    env_enabled: true
    windows_activation_enabled: true
    firewall_logging_enabled: false
    optional_fw_rules_enabled: false
    vpc_flow_logs_enabled: false
    peering_iap_fw_rules_enabled: false
    base:
      enabled:   true
      projects:
        - id: proj_base_prod_pub_s1
          type: service
          app:  pub_base_prod_s1
        - id: proj_base_prod_app_s1
          type: service
          app:  app_base_prod_s1
        - id: proj_base_prod_dat_s1
          type: service
          app:  data_base_prod_s1

- business_code: "bu2"
  business_unit: "business_unit_2"
  primary_contact: "example_p2@example.com"
  secondary_contact: "example_s2@example.com"
  identity:
    env_code: "i"
    billing_code: "i-bu2"
    env_enabled: true
    windows_activation_enabled: true
    firewall_logging_enabled: false
    optional_fw_rules_enabled: false
    vpc_flow_logs_enabled: false
    peering_iap_fw_rules_enabled: false
    base:
      enabled:   true
      projects:
        - id: proj_base_idn_s2
          type: service
          app:  idn_base_s2

  development:
    env_code: "d"
    billing_code: "d-bu2"
    env_enabled: true
    windows_activation_enabled: true
    firewall_logging_enabled: false
    optional_fw_rules_enabled: false
    vpc_flow_logs_enabled: false
    peering_iap_fw_rules_enabled: false
    base:
      enabled:   true
      projects:
        - id: proj_base_dev_pub_s2
          type: service
          app:  pub_base_dev_s2
        - id: proj_base_dev_app_s2
          type: service
          app:  app_base_dev_s2
        - id: proj_base_dev_dat_s2
          type: service
          app:  data_base_dev_s2
  nonproduction:
    env_code: "n"
    env_enabled: true
    windows_activation_enabled: true
    firewall_logging_enabled: false
    optional_fw_rules_enabled: false
    vpc_flow_logs_enabled: false
    peering_iap_fw_rules_enabled: false
    base:
      enabled:   true
      projects:
        - id: proj_base_np_pub_s2
          type: service
          app:  pub_base_np_s2
        - id: proj_base_np_app_s2
          type: service
          app:  app_base_np_s2
        - id: proj_base_np_dat_s2
          type: service
          app:  data_base_np_s2
  production:
    env_code: "p"
    env_enabled: true
    windows_activation_enabled: true
    firewall_logging_enabled: false
    optional_fw_rules_enabled: false
    vpc_flow_logs_enabled: false
    peering_iap_fw_rules_enabled: false
    base:
      enabled:   true
      projects:
        - id: proj_base_prod_pub_s2
          type: service
          app:  pub_base_prod_s2
        - id: proj_base_prod_app_s2
          type: service
          app:  app_base_prod_s2
        - id: proj_base_prod_dat_s2
          type: service
          app:  data_base_prod_s2
    restricted:
      enabled:   true
      vpc_scp:   true
      projects:
        - id: proj_restr_prod_pub_s1
          type: service
          app:  pub_restr_prod_s2
        - id: proj_restr_prod_app_s2
          type: service
          app:  app_restr_prod_s2
        - id: proj_restr_prod_dat_s2
          type: service
          app:  data_restr_prod_s2






