# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
# Codes from GC naming doc, currently used for reference only.  Currently no framework exists for GCP.
# Based on: https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/naming-and-tagging
types:
  # <code> : description
  prj: "Project"
  folder: "Folder"
  vpc: "VPC Network"
  snet: "VPC Subnet"
  route: "Route"
  router: "Cloud Router"
  nat: "Cloud NAT"
  vm : "Virtual Machine"
  pip# : "Public IP Address"
  fw : "Firewall"
  fwr: "Firewall Rule"
  stg : "Storage Bucket"
  sink: "Log Export Sink"
  acm: "Access Context Manager"
  acml: "Access Context Manager Level"
  acmp: "Access Context Manager Perimeter"
  gcb: "Google Cloud Build"
  gcbt: "Google Cloud Build Trigger"
  sjob: "Google CLoud Scheduler Job"
  sa: "Service Account"
  cbt: "Cloud Build Trigger"
  csj: "Cloud Scheduler Job"
  cf: "Cloud Function"
  vsc: "VPC SVC Controls"
  role: "Custom Role"
  cntr: "Container"
  csr: "Cloud Source Repository"
  