# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
# Codes from GC naming doc, currently used for reference only
character1 :
  codes :
    S : "Virtual Machine / Server"
character2 :
  codes :
    W : "Windows OS"
    L : "RedHat Enterprise Linux or SUSE Linux Enterprise Server"
    A : "Appliance based server (not OS specific)"
    X : "Hypervisor"
character3 :
  codes :
    A : "Domain Services (Active Directory, DNS, DHCP, etc.)"
    B : "Data bases (Oracle, MS-SQL, etc.)"
    C : "Web Servers [http/https only] (Apache, IIS, etc.)"
    D : "Application Servers (Web Trends, PeopleSoft, SAP, Web Application Servers [WebLogic, WebSphere, Tomcat], etc.)"
    E : "Management Servers (venter, SCOM, SCCM, Puppet, etc.)"
    F : "File and Print Servers"
    G : "Clusters"
    H : "Messaging"
    V : "Microsoft Hyper-V"
    X : "VMWare ESX"
    J : "Jump Server"
